module.exports = {
  PAGINATION: {
    DEFAULT_LIMIT: 20,
    MAX_LIMIT: 100
  },
  TIME_SLOTS: {
    MAX_RECURRING_SLOTS: 52,
    MIN_DURATION_MINUTES: 30,
    MAX_FUTURE_DAYS: 365
  },
  ERROR_CODES: {
    UNIQUE_VIOLATION: '23505',
    FOREIGN_KEY_VIOLATION: '23503'
  }
}; 